"""
Second iteration of the flower hist app
"""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Imports

from __future__ import annotations

# General imports
import numpy as np
import pandas as pd
import toml

# Flower imports
from flwr.common import Context, Message, MetricRecord, RecordDict

# Internal imports
from clinnova_fl.data_connector.generic import data_connector

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

def query(msg : Message, context : Context, data_connector : data_connector):
    """
    Construct histogram of local dataset and report to `ServerApp`.
    """
    
    """
    Example of msg and context.

    Note for the Message 
    All the info in metadata should be generated by the Flower framework. The only expection is the message_type, which can be set by the user if the Message API is used.
    The content of the message is set by the user, and it consist in the data that are exchanged between the server and the clients. content will always be an istance of the RecordDict class.
    TLDR : Directly from the flower webpage. `A dictionary mapping string keys to record instances, where each value is either a ParametersRecord, MetricsRecord, or ConfigsRecord.`
    See https://flower.ai/docs/framework/ref-api/flwr.common.RecordDict.html for more details about the RecordDict class.
    For more info about the Message see https://flower.ai/docs/framework/ref-api/flwr.common.Message.html

    Note for the Context
    run_id and node_id are generated by the Flower framework.
    node_config are config specific for each node, and they are "static", i.e. they do not change during the execution of the app. They are passed as arguments of the flower-supernode command when the node is created.
    It is not possible to create custom node config during flower simulation.
    run_config are config specific for the whole run and they are received from the server. Usually the are specified in the server code and sent to the clients at the beginning of the run, but they can be updated during the run by the server and sent to the clients.
    state should be used to store any information that the client wants to keep during the run. Each data added to state should be available in the next rounds of the same run. Note that each node can access only to its own state, and not to the state of the other nodes.
    For more info about the Context see https://flower.ai/docs/framework/ref-api/flwr.common.Context.html

    Message(
        metadata=Metadata(
            run_id=8348619855088795003,
            message_id='f12007fe252d28bb0f86e7216a657c78588403b20763751b87d4d27a5835486f',
            src_node_id=1, dst_node_id=11631752601818482563,
            reply_to_message_id='',
            group_id='1', 
            created_at=1759151430.732682,
            ttl=43200.0, 
            message_type='query',
            delivered_at=''
        ),
        content=RecordDict(
          array_records={},
          metric_records={},
          config_records={}
        )
    )

    Context(
        run_id=8348619855088795003,
        node_id=11631752601818482563,
        node_config={'num-partitions': 2, 'partition-id': 1},
        state=RecordDict(
            array_records={},
            metric_records={},
            config_records={}
        ),
        run_config={'num-server-rounds': 3, 'fraction-sample': 1.0}
    )
    """

    # Get config (from the message)
    my_config = msg.content.config_records["my_config"]

    # Histogram parameters
    server_round  = my_config["server_round"]
    bins_variable = my_config["bins_variable"]
    
    # Get the dataset
    data_to_calculate_hist = data_connector.get_data_array()
    
    # Variable to store the results of the query
    query_results = {}

    if server_round == 0 :
        # Min-max computation
        query_results["min"] = np.min(data_to_calculate_hist).item()
        query_results["max"] = np.max(data_to_calculate_hist).item()
    elif server_round == 1 :
        # Histogram computation

        # Get bins from the message sent by the server
        bins = my_config["bins"]

        # Compute histogram
        freqs_all, _ = np.histogram(data_to_calculate_hist, bins = bins)
    
        # Save the histogram
        query_results["histogram"] = freqs_all.tolist()

        # Save average and std
        query_results["average"] = np.mean(data_to_calculate_hist).item()
        query_results["std"]     = np.std(data_to_calculate_hist).item()
    else :
        raise ValueError(f"Server round {server_round} not supported.")

    reply_content = RecordDict({"query_results": MetricRecord(query_results)})

    return Message(reply_content, reply_to = msg)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# def update_data_connector_config(my_config : dict, data_connector_config : connector.csv.csv_connector_config) :
#     """
#     Update the data_connector_config with the name of the variable on which you want to compute the histogram
#     """
#
#     if data_connector_config.






