[project]
name = "Clinnova_Federated_ml_linear_training_PoC"
version = "1.0.0"
description = "Proof of Concept (PoC) for the training of a linear classifier in a federated environment"
license = "Apache-2.0"
authors = [
    { name = "Alberto Zancanaro", email = "alberto.zancanaro@uni.lu" },
]
dependencies = [
    "flwr[simulation]>=1.22.0",
    "numpy>=2.0.2",
    "pandas==2.2.3",
	"sklearn"
]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "server_app:app"
clientapp = "client_app:app"

[tool.flwr.app.config]
path_server_config = ''

[tool.flwr.federations]
default = "local-deployment"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
options.backend.client-resources.num-gpus = 1
options.backend.client-resources.num-cpus = 1
options.backend.init_args.num_cpus = 1
options.backend.init_args.num_gpus = 1

[tool.flwr.federations.local-deployment]
address = "127.0.0.1:9093"
insecure = true # To run with insecure connection

