"""
@author: Alberto Zancanaro (Jesus)
@organization: Luxembourg Centre for Systems Biomedicine (LCSB)
@contact : alberto.zancanaro@uni.lu
@date: September 2025
"""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Imports

import numpy as np
import pandas as pd

from collections.abc import Iterable

from flwr.client import ClientApp
from flwr.common import Context, Message, MetricRecord, RecordDict

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create a Flower ClientApp instance. Note that the istance is called `app`, the same name used in the pyproject.toml file
# The app istance allow us to use the decorator provided by the Flower framework.
app = ClientApp()

# The query() decorator allow us to define a function that will be called when the client receive a message of type "query" from the server. 
# The function always receive two arguments: the message received from the server and the context of the client. The function should return a message that will be sent back to the server as a reply to the query.
@app.query()
def query(msg : Message, context : Context):
    """
    Construct histogram of local dataset and report to `ServerApp`.
    """

    """
    Example of msg and context

    Note for the Message 
    All the info in metadata should be generated by the Flower framework. The only expection is the message_type, which can be set by the user if the Message API is used.
    The content of the message is set by the user, and it consist in the data that are exchanged between the server and the clients. content will always be an istance of the RecordDict class.
    TLDR : Directly from the flower webpage. `A dictionary mapping string keys to record instances, where each value is either a ParametersRecord, MetricsRecord, or ConfigsRecord.`
    See https://flower.ai/docs/framework/ref-api/flwr.common.RecordDict.html for more details about the RecordDict class.
    For more info about the Message see https://flower.ai/docs/framework/ref-api/flwr.common.Message.html

    Note for the Context
    run_id and node_id are generated by the Flower framework.
    node_config are config specific for each node, and they are "static", i.e. they do not change during the execution of the app. They are passed as arguments of the flower-supernode command when the node is created.
    It is not possible to create custom node config during flower simulation.
    run_config are config specific for the whole run and they are received from the server. Usually the are specified in the server code and sent to the clients at the beginning of the run, but they can be updated during the run by the server and sent to the clients.
    state should be used to store any information that the client wants to keep during the run. Each data added to state should be available in the next rounds of the same run. Note that each node can access only to its own state, and not to the state of the other nodes.
    For more info about the Context see https://flower.ai/docs/framework/ref-api/flwr.common.Context.html

    Message(
        metadata=Metadata(
            run_id=8348619855088795003,
            message_id='f12007fe252d28bb0f86e7216a657c78588403b20763751b87d4d27a5835486f',
            src_node_id=1, dst_node_id=11631752601818482563,
            reply_to_message_id='',
            group_id='1',
            created_at=1759151430.732682,
            ttl=43200.0,
            message_type='query',
            delivered_at=''
        ),
        content=RecordDict(
          array_records={},
          metric_records={},
          config_records={}
        )
    )

    Context(
        run_id=8348619855088795003,
        node_id=11631752601818482563,
        node_config={'num-partitions': 2, 'partition-id': 1},
        state=RecordDict(
            array_records={},
            metric_records={},
            config_records={}
        ),
        run_config={'num-server-rounds': 3, 'fraction-sample': 1.0}
    )
    """

    # Get config (from the message)
    my_config       = msg.content.config_records["my_config"]
    server_round    = my_config["server_round"]
    bins_variable   = my_config["bins_variable"] # Not used in V1
    
    # Create syntethic data
    data_hist_all     = np.random.normal(loc = 0, scale = 1, size = 1000)

    # Divide the data into three groups (UC, CD, Control)
    data_hist_UC      = data_hist_all[:333]
    data_hist_CD      = data_hist_all[333:666]
    data_hist_control = data_hist_all[666:]

    query_results = {}

    if server_round == 0 :
        # Min-max computation
        query_results["min"] = np.min(data_hist_all).item()
        query_results["max"] = np.max(data_hist_all).item()
    elif server_round == 1 :
        # Histogram computation

        # Get bins from the message sent by the server
        bins = my_config["bins"]

        # Compute histogram
        freqs_all, _     = np.histogram(data_hist_all, bins = bins)
        freqs_UC, _      = np.histogram(data_hist_UC, bins = bins)
        freqs_CD, _      = np.histogram(data_hist_CD, bins = bins)
        freqs_control, _ = np.histogram(data_hist_control, bins = bins)
    
        # Save the histogram
        query_results["histogram_all"]     = freqs_all.tolist()
        query_results["histogram_UC"]      = freqs_UC.tolist()
        query_results["histogram_CD"]      = freqs_CD.tolist()
        query_results["histogram_control"] = freqs_control.tolist()

        # Save average and std
        query_results["average_all"]     = np.mean(data_hist_all).item()
        query_results["std_all"]         = np.std(data_hist_all).item()
        query_results["average_UC"]      = np.mean(data_hist_UC).item()
        query_results["std_UC"]          = np.std(data_hist_UC).item()
        query_results["average_CD"]      = np.mean(data_hist_CD).item()
        query_results["std_CD"]          = np.std(data_hist_CD).item()
        query_results["average_control"] = np.mean(data_hist_control).item()
        query_results["std_control"]     = np.std(data_hist_control).item()
    else :
        raise ValueError(f"Server round {server_round} not supported.")

    reply_content = RecordDict({"query_results": MetricRecord(query_results)})

    return Message(reply_content, reply_to = msg)
