# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# NON FLOWER SETTINGS


[project]
name = "Clinnova_Federated_Hist_PoC"
version = "1.0.0"
description = "Proof of Concept (PoC) for a computation of histograms in a federated environment"
license = "Apache-2.0"
authors = [
    { name = "Alberto Zancanaro", email = "alberto.zancanaro@uni.lu" },
]
dependencies = [
    "flwr[simulation]>=1.22.0",
    "numpy>=2.0.2",
    "pandas==2.2.3",
	"matplotlib"
]

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FLOWER SETTINGS

[tool.flwr.app]
publisher = "Biocore"

[tool.flwr.app.components]
# Name of the server and client app. It should be in the format "module_name:app_object_name". 
# The module name is the name of the python file where the app object is defined (without the .py extension). The path to the file should be relative to the root of the project.
# The app object name is the name of the variable that contains the app object in the python file.
serverapp = "server_app:app"
clientapp = "client_app:app"

# P.s. Note that (theoretically) you don't have to use two files to define ClientApp and ServerApp. You could use the same file and create two variable with different names inside it.
# But usually it is preferable to keep things separate for greater cleanliness and clarity.

[tool.flwr.app.config]
# This are the config that appears in the run_config object inside the python scripts
path_server_config = ""

[tool.flwr.federations]
# Federation to use by default to run your app if no federation is specified with the flwr run command
# It should be also the federation selected when you simulate the app with nvflare
default = "local-deployment"

[tool.flwr.federations.local-simulation]
# Setting specific for a federation (in this case the local-simulation federation)
# Since it is a simulation I do not need to specify the address of the server but only the available hardware
options.num-supernodes = 2
options.backend.client-resources.num-gpus = 1
options.backend.client-resources.num-cpus = 1
options.backend.init_args.num_cpus = 1
options.backend.init_args.num_gpus = 1

[tool.flwr.federations.local-deployment]
# Setting for another federation. 
# In this case, since it is a local deployment, i.e. I created the superlink and supernode inside my local machine
# In fact the address of the server is the local address and I do not need to specify any resource since I am using the resources of my local machine
# The insecure flag is set to true since I am running with an insecure connection, without TLS. If I want to run with TLS I need to set this flag to false and specify the path to the root certificate of the CA that signed the certificate of the server
address = "127.0.0.1:9093"
insecure = true # To run with insecure connection
# root-certificates = "certificates/ca.crt" # To run with TLS (secure) connection

